-- MySQL Script generated by MySQL Workbench
-- Mon Aug  6 12:18:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ezmart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ezmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ezmart` DEFAULT CHARACTER SET utf8 ;
USE `ezmart` ;

-- -----------------------------------------------------
-- Table `ezmart`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`state` (
  `state_id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(30) NOT NULL,
  `state_initials` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`state_id`),
  UNIQUE INDEX `state_name` (`state_name` ASC),
  UNIQUE INDEX `state_initials` (`state_initials` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`city` (
  `city_id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(30) NOT NULL,
  `city_codeibge` VARCHAR(10) NOT NULL,
  `city_stateid` INT(11) NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_codeibge` (`city_codeibge` ASC),
  INDEX `fk1_city` (`city_stateid` ASC),
  CONSTRAINT `fk1_city`
    FOREIGN KEY (`city_stateid`)
    REFERENCES `ezmart`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`usersystem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`usersystem` (
  `usersystem_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usersystem_email` VARCHAR(100) NOT NULL,
  `usersystem_password` VARCHAR(30) NOT NULL,
  `usersystem_addresslocation` VARCHAR(100) NOT NULL,
  `usersystem_numberhouse` VARCHAR(10) NOT NULL,
  `usersystem_neighborhood` VARCHAR(100) NOT NULL,
  `usersystem_cityid` INT(11) NOT NULL,
  `usersystem_zipcode` VARCHAR(10) NOT NULL,
  `usersystem_telephone` VARCHAR(15) NOT NULL,
  `usersystem_usertype` VARCHAR(20) NOT NULL,
  `usersystem_latitude` VARCHAR(10) NULL DEFAULT NULL,
  `usersystem_longitude` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`usersystem_id`),
  UNIQUE INDEX `usersystem_email` (`usersystem_email` ASC),
  INDEX `fk1_usersystem` (`usersystem_cityid` ASC),
  CONSTRAINT `fk1_usersystem`
    FOREIGN KEY (`usersystem_cityid`)
    REFERENCES `ezmart`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`consumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`consumer` (
  `consumer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `consumer_name` VARCHAR(250) NOT NULL,
  `consumer_lastname` VARCHAR(100) NOT NULL,
  `consumer_cpf` VARCHAR(11) NOT NULL,
  `consumer_userid` INT(11) NOT NULL,
  PRIMARY KEY (`consumer_id`),
  UNIQUE INDEX `consumer_cpf` (`consumer_cpf` ASC),
  INDEX `fk1_consumer` (`consumer_userid` ASC),
  CONSTRAINT `fk1_consumer`
    FOREIGN KEY (`consumer_userid`)
    REFERENCES `ezmart`.`usersystem` (`usersystem_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`establishment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`establishment` (
  `establishment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `establishment_cnpj` VARCHAR(14) NOT NULL,
  `establishment_secondemail` VARCHAR(100) NOT NULL,
  `establishment_name` VARCHAR(100) NULL DEFAULT NULL,
  `establishment_businessname` VARCHAR(100) NOT NULL,
  `establishment_plan` INT(11) NULL DEFAULT NULL,
  `establishment_planstartdate` DATE NULL DEFAULT NULL,
  `establishment_planfinaldate` DATE NULL DEFAULT NULL,
  `establishment_userid` INT(11) NOT NULL,
  PRIMARY KEY (`establishment_id`),
  UNIQUE INDEX `establishment_cnpj` (`establishment_cnpj` ASC),
  INDEX `fk1_establishment` (`establishment_userid` ASC),
  CONSTRAINT `fk1_establishment`
    FOREIGN KEY (`establishment_userid`)
    REFERENCES `ezmart`.`usersystem` (`usersystem_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`avaliation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`avaliation` (
  `avaliation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `avaliation_satisfaction` INT(11) NOT NULL,
  `avaliation_productprice` INT(11) NOT NULL,
  `avaliation_diversity` INT(11) NOT NULL,
  `avaliation_employees` INT(11) NOT NULL,
  `avaliation_ambience` INT(11) NOT NULL,
  `avaliation_commentary` VARCHAR(100) NULL DEFAULT NULL,
  `avaliation_consumerid` INT(11) NOT NULL,
  `avaliation_establishmentid` INT(11) NOT NULL,
  `avaliation_date` DATE NOT NULL,
  PRIMARY KEY (`avaliation_id`),
  INDEX `fk1_avaliation` (`avaliation_consumerid` ASC),
  INDEX `fk2_avaliation` (`avaliation_establishmentid` ASC),
  CONSTRAINT `fk1_avaliation`
    FOREIGN KEY (`avaliation_consumerid`)
    REFERENCES `ezmart`.`consumer` (`consumer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk2_avaliation`
    FOREIGN KEY (`avaliation_establishmentid`)
    REFERENCES `ezmart`.`establishment` (`establishment_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`promotion` (
  `promotion_id` INT(11) NOT NULL AUTO_INCREMENT,
  `promotion_name` VARCHAR(50) NULL DEFAULT NULL,
  `promotion_startdate` DATE NOT NULL,
  `promotion_finaldate` DATE NOT NULL,
  PRIMARY KEY (`promotion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`provider` (
  `provider_id` INT(11) NOT NULL DEFAULT '0',
  `provider_cnpj` VARCHAR(20) NOT NULL,
  `provider_name` VARCHAR(100) NULL DEFAULT NULL,
  `provider_businessname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`provider_id`),
  UNIQUE INDEX `provider_cnpj` (`provider_cnpj` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`sector` (
  `sector_id` INT(11) NOT NULL DEFAULT '0',
  `sector_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`sector_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_sectorid` INT(11) NOT NULL,
  `product_providerid` INT(11) NOT NULL,
  `product_barcode` VARCHAR(15) NOT NULL,
  `product_name` VARCHAR(150) NOT NULL,
  `product_image` BLOB NULL DEFAULT NULL,
  `product_brand` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk1_product` (`product_sectorid` ASC),
  INDEX `fk2_product` (`product_providerid` ASC),
  CONSTRAINT `fk2_product`
    FOREIGN KEY (`product_providerid`)
    REFERENCES `ezmart`.`provider` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk1_product`
    FOREIGN KEY (`product_sectorid`)
    REFERENCES `ezmart`.`sector` (`sector_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`establishmentproduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`establishmentproduct` (
  `establishmentproduct_id` INT(11) NOT NULL AUTO_INCREMENT,
  `establishmentproduct_establishmentid` INT(11) NOT NULL,
  `establishmentproduct_productid` INT(11) NOT NULL,
  `establishmentproduct_price` VARCHAR(10) NOT NULL,
  `establishmentproduct_promotionid` INT(11) NULL DEFAULT NULL,
  `establishmentproduct_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`establishmentproduct_id`),
  INDEX `fk1_establishmentproduct` (`establishmentproduct_establishmentid` ASC),
  INDEX `fk2_establishmentproduct` (`establishmentproduct_productid` ASC),
  INDEX `fk3_establishmentproduct` (`establishmentproduct_promotionid` ASC),
  CONSTRAINT `fk3_establishmentproduct`
    FOREIGN KEY (`establishmentproduct_promotionid`)
    REFERENCES `ezmart`.`promotion` (`promotion_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk1_establishmentproduct`
    FOREIGN KEY (`establishmentproduct_establishmentid`)
    REFERENCES `ezmart`.`establishment` (`establishment_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk2_establishmentproduct`
    FOREIGN KEY (`establishmentproduct_productid`)
    REFERENCES `ezmart`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`list` (
  `list_id` INT(11) NOT NULL AUTO_INCREMENT,
  `list_consumerid` INT(11) NOT NULL,
  `list_favorite` TINYINT(1) NULL DEFAULT '0',
  `list_name` VARCHAR(50) NULL DEFAULT 'Sem nome',
  `list_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`list_id`),
  INDEX `fk1_list` (`list_consumerid` ASC),
  CONSTRAINT `fk1_list`
    FOREIGN KEY (`list_consumerid`)
    REFERENCES `ezmart`.`consumer` (`consumer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ezmart`.`listproduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezmart`.`listproduct` (
  `listproduct_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `listproduct_listid` INT(11) NOT NULL,
  `listproduct_productid` INT(11) NOT NULL,
  `listproduct_quantity` INT(11) NOT NULL,
  PRIMARY KEY (`listproduct_id`),
  INDEX `fk1_listproduct` (`listproduct_listid` ASC),
  INDEX `fk2_listproduct` (`listproduct_productid` ASC),
  CONSTRAINT `fk2_listproduct`
    FOREIGN KEY (`listproduct_productid`)
    REFERENCES `ezmart`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk1_listproduct`
    FOREIGN KEY (`listproduct_listid`)
    REFERENCES `ezmart`.`list` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
